#!/usr/bin/env python3
"""Build notebooks/cot_batch_colab.ipynb (standalone Colab batch runner)."""
import json

MD = "markdown"
CODE = "code"

cells = []

cells.append({
    "cell_type": MD,
    "metadata": {},
    "source": [
        "# C3PA QSBC — Standalone CoT Batch Runner (Colab)\n",
        "\n",
        "Runs the QSBC Phase-1 reasoning generation against a **local** model\n",
        "(Gemma 4 via Ollama) directly in Colab — no FastAPI/Postgres/opencode\n",
        "needed. Parsing and prompt construction reuse the repo's exact logic, so\n",
        "payloads match the API-driven batches byte-for-byte.\n",
        "\n",
        "**Resume-safe:** sampling uses a deterministic per-label seeded shuffle\n",
        "(`SEED + label_id`) and takes the next `PER_LABEL` sentences not already in\n",
        "`results/`. Each run advances through the same permutation, so committing\n",
        "the shard files back to GitHub lets the next session continue exactly where\n",
        "this one left off. Results are written incrementally (a session death loses\n",
        "at most a few rows).\n",
        "\n",
        "**Output:** `results/reasonings_<start>-<end>.json`, one file per 500 rows\n",
        "(`SHARD_SIZE`). Download them (cell 7) and commit to the repo to resume later.\n",
        "\n",
        "**Knobs:** `MODEL`, `PER_LABEL`, `DOC_LIMIT`, `MIN_N`/`MAX_N`, `SEED`,\n",
        "`RUN_ID`, `MAX_WORKERS`, `SHARD_SIZE`.\n"
    ],
})

cells.append({
    "cell_type": CODE,
    "metadata": {},
    "source": [
        "# 1. Clone repo + dataset\n",
        "import os, sys\n",
        "os.chdir('/content')\n",
        "if not os.path.exists('/content/qsbc'):\n",
        "    !git clone -q https://github.com/jpeckenpaugh/qsbc.git qsbc\n",
        "    !git clone -q https://github.com/MaazBinMusa/C3PA_Dataset.git qsbc/C3PA_Dataset\n",
        "os.chdir('/content/qsbc')\n",
        "sys.path.insert(0, '/content/qsbc')\n",
        "print('cwd:', os.getcwd())\n",
        "print('repo files:', sorted(os.listdir('.'))[:12])\n",
        "print('existing results shards:', sorted(os.listdir('results')) if os.path.isdir('results') else 'none')\n"
    ],
})

cells.append({
    "cell_type": CODE,
    "metadata": {},
    "source": [
        "# 2. Parse C3PA -> data/*.tsv (exact same pipeline as the local DB)\n",
        "!python scripts/parse_c3pa.py\n"
    ],
})

cells.append({
    "cell_type": CODE,
    "metadata": {},
    "source": [
        "# 3. Install + start Ollama, pull model\n",
        "import subprocess, time, os, requests\n",
        "\n",
        "MODEL = 'gemma4:26b-a4b-it-q4_K_M'   # 26B-A4B MoE, 18GB -> needs L4/A100 (Colab Pro)\n",
        "\n",
        "if not os.path.exists('/usr/local/bin/ollama'):\n",
        "    # zstd for the installer; pciutils/lshw so Ollama can detect the Colab GPU\n",
        "    !sudo apt-get install -y -q zstd pciutils lshw\n",
        "    !curl -fsSL https://ollama.com/install.sh | sh\n",
        "\n",
        "if not os.popen('pgrep -x ollama').read().strip():\n",
        "    subprocess.Popen(['ollama', 'serve'], stdout=subprocess.DEVNULL,\n",
        "                     stderr=subprocess.DEVNULL)\n",
        "    for _ in range(30):\n",
        "        try:\n",
        "            requests.get('http://localhost:11434/api/tags', timeout=2)\n",
        "            break\n",
        "        except Exception:\n",
        "            time.sleep(2)\n",
        "\n",
        "!ollama pull {MODEL}\n",
        "print('model ready:', requests.get('http://localhost:11434/api/tags').json())\n"
    ],
})

cells.append({
    "cell_type": CODE,
    "metadata": {},
    "source": [
        "# 4. Load parsed TSVs -> in-memory corpus (COPY-compatible text decoding)\n",
        "import csv, random\n",
        "from collections import defaultdict\n",
        "from app.promptlib import build_payload, render_prompt\n",
        "\n",
        "def read_tsv(path):\n",
        "    rows = []\n",
        "    with open(path, newline='', encoding='utf-8') as fh:\n",
        "        for row in csv.reader(fh, delimiter='\\t'):\n",
        "            if not row:\n",
        "                continue\n",
        "            # undo COPY's backslash unescaping so text matches the local DB\n",
        "            rows.append([c.replace('\\\\\\\\', '\\\\') for c in row])\n",
        "    return rows\n",
        "\n",
        "labels   = {int(i): name for i, name in read_tsv('data/labels.tsv')}\n",
        "documents = {int(i): {'subset': s, 'doc_key': k}\n",
        "             for i, s, n, f, k, u in read_tsv('data/documents.tsv')}\n",
        "sentences = {int(i): (int(d), t) for i, d, t in read_tsv('data/sentences.tsv')}\n",
        "\n",
        "sentence_labels = defaultdict(set)\n",
        "for sid, lid in read_tsv('data/sentence_labels.tsv'):\n",
        "    sentence_labels[int(sid)].add(int(lid))\n",
        "\n",
        "# single-label only, excluding 'Others'\n",
        "single = {sid: next(iter(lids)) for sid, lids in sentence_labels.items()\n",
        "          if len(lids) == 1 and labels[next(iter(lids))] != 'Others'}\n",
        "\n",
        "# (doc_id, label_id) -> ordered [(sentence_id, text)]  (id == document order)\n",
        "groups = defaultdict(list)\n",
        "for sid, lid in single.items():\n",
        "    did, text = sentences[sid]\n",
        "    groups[(did, lid)].append((sid, text))\n",
        "for k in groups:\n",
        "    groups[k].sort()\n",
        "\n",
        "print('single-label sentences:', len(single), '| groups:', len(groups))\n"
    ],
})

cells.append({
    "cell_type": CODE,
    "metadata": {},
    "source": [
        "# 5. Sample per-label: seeded shuffle, skip already-done (resume-safe)\n",
        "import json, random, os, glob\n",
        "\n",
        "PER_LABEL = 4      # new sentences per label this run\n",
        "DOC_LIMIT = 15     # centered window over same-label sentences\n",
        "MIN_N, MAX_N = 2, 5\n",
        "SEED = 42\n",
        "RESULTS_DIR = 'results'\n",
        "\n",
        "# done-set: every sentence_id already present in committed/previous shards\n",
        "done = set()\n",
        "if os.path.isdir(RESULTS_DIR):\n",
        "    for f in sorted(glob.glob(os.path.join(RESULTS_DIR, 'reasonings_*.json'))):\n",
        "        with open(f) as fh:\n",
        "            for rec in json.load(fh):\n",
        "                done.add(rec['sentence_id'])\n",
        "print('already done:', len(done))\n",
        "\n",
        "by_label = defaultdict(list)\n",
        "for (did, lid), items in groups.items():\n",
        "    for sid, text in items:\n",
        "        by_label[lid].append((sid, did, text))\n",
        "\n",
        "tasks = []\n",
        "for lid in sorted(by_label):\n",
        "    rng = random.Random(SEED + lid)          # deterministic per label\n",
        "    pool_list = sorted(by_label[lid])\n",
        "    rng.shuffle(pool_list)\n",
        "    picked = [x for x in pool_list if x[0] not in done][:PER_LABEL]\n",
        "    for sid, did, text in picked:\n",
        "        ordered = groups[(did, lid)]\n",
        "        target_index = next(i for i, (s, t) in enumerate(ordered) if s == sid)\n",
        "        tasks.append({\n",
        "            'sentence_id': sid,\n",
        "            'doc_id': did,\n",
        "            'label_id': lid,\n",
        "            'label': labels[lid],\n",
        "            'doc_key': documents[did]['doc_key'],\n",
        "            'doc_total': len(ordered),\n",
        "            'payload': build_payload(text, labels[lid],\n",
        "                                    [t for s, t in ordered], target_index,\n",
        "                                    DOC_LIMIT),\n",
        "        })\n",
        "\n",
        "print('new tasks this run:', len(tasks))\n",
        "if tasks:\n",
        "    print('sample payload:', json.dumps(tasks[0]['payload'], ensure_ascii=False)[:200])\n"
    ],
})

cells.append({
    "cell_type": CODE,
    "metadata": {},
    "source": [
        "# 6. Run batch: per-task retry, incremental shard save (session-safe)\n",
        "import requests, time, os\n",
        "from concurrent.futures import ThreadPoolExecutor\n",
        "from app.extract import extract_json_array\n",
        "\n",
        "RUN_ID = 'colab-gemma4-01'   # unique per batch; kept on every row\n",
        "MAX_WORKERS = 4\n",
        "SHARD_SIZE = 500\n",
        "OLLAMA_URL = 'http://localhost:11434/v1/chat/completions'\n",
        "\n",
        "os.makedirs(RESULTS_DIR, exist_ok=True)\n",
        "shard_base = len(done)\n",
        "shard_path = os.path.join(RESULTS_DIR,\n",
        "    f'reasonings_{shard_base:04d}-{shard_base + SHARD_SIZE - 1:04d}.json')\n",
        "print('shard file:', shard_path)\n",
        "\n",
        "def call_once(task):\n",
        "    prompt = render_prompt(task['payload'], min_n=MIN_N, max_n=MAX_N,\n",
        "                           generalize=True)\n",
        "    r = requests.post(\n",
        "        OLLAMA_URL,\n",
        "        json={'model': MODEL,\n",
        "              'messages': [{'role': 'user', 'content': prompt}],\n",
        "              'temperature': 0.05,\n",
        "              'stream': False},\n",
        "        timeout=600,\n",
        "    )\n",
        "    r.raise_for_status()\n",
        "    return r.json()['choices'][0]['message']['content'].strip()\n",
        "\n",
        "def generate(task):\n",
        "    last_err = None\n",
        "    for attempt in range(2):   # light retry\n",
        "        try:\n",
        "            raw = call_once(task)\n",
        "            status, _ = extract_json_array(raw)\n",
        "            return {**task, 'run_id': RUN_ID, 'model': MODEL,\n",
        "                    'raw_response': raw, 'parse_status': status}\n",
        "        except Exception as e:\n",
        "            last_err = e\n",
        "            time.sleep(5 * (attempt + 1))\n",
        "    return {**task, 'run_id': RUN_ID, 'model': MODEL, 'raw_response': '',\n",
        "            'parse_status': 'error', 'error': str(last_err)[:200]}\n",
        "\n",
        "results = []\n",
        "with ThreadPoolExecutor(max_workers=MAX_WORKERS) as pool:\n",
        "    futures = [pool.submit(generate, t) for t in tasks]\n",
        "    n = 0\n",
        "    for f in futures:\n",
        "        res = f.result()\n",
        "        results.append(res)\n",
        "        n += 1\n",
        "        with open(shard_path, 'w') as fh:      # incremental: survives resets\n",
        "            json.dump(results, fh, indent=2, ensure_ascii=False)\n",
        "        print(f\"[{n}/{len(tasks)}] #{res['sentence_id']} {res['parse_status']} \"\n",
        "              f\"({len(res['raw_response'])} chars)\")\n",
        "\n",
        "from collections import Counter\n",
        "print('parse_status:', dict(Counter(r['parse_status'] for r in results)))\n",
        "print('shard saved:', shard_path, f'({len(results)} rows)')\n"
    ],
})

cells.append({
    "cell_type": CODE,
    "metadata": {},
    "source": [
        "# 7. Download shard(s) + commit back (resume)\n",
        "from google.colab import files\n",
        "\n",
        "for f in sorted(os.listdir(RESULTS_DIR)):\n",
        "    if f.startswith('reasonings_'):\n",
        "        files.download(os.path.join(RESULTS_DIR, f))\n",
        "\n",
        "# Commit the shard back to GitHub so the next Colab session resumes.\n",
        "# Colab clones use HTTPS, so set a token first (once per session):\n",
        "#   !git remote set-url origin https://<PAT>@github.com/jpeckenpaugh/qsbc.git\n",
        "# then uncomment:\n",
        "# !git add results/ && git commit -m 'add reasoning shard' && git push -q origin HEAD:main\n",
        "\n",
        "# Optional: also stash a copy on Drive if mounted\n",
        "if os.path.exists('/content/drive/MyDrive'):\n",
        "    os.makedirs('/content/drive/MyDrive/qsbc_results', exist_ok=True)\n",
        "    for f in sorted(os.listdir(RESULTS_DIR)):\n",
        "        if f.startswith('reasonings_'):\n",
        "            !cp {os.path.join(RESULTS_DIR, f)} /content/drive/MyDrive/qsbc_results/\n"
    ],
})

notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {"colab": {}, "kernelspec": {"name": "python3", "display_name": "Python 3"},
                 "language_info": {"name": "python"}},
    "cells": cells,
}

with open("notebooks/cot_batch_colab.ipynb", "w") as fh:
    json.dump(notebook, fh, indent=1)
print("wrote notebooks/cot_batch_colab.ipynb with", len(cells), "cells")